### ISSUE TITLE
error after leader closed

### ISSUE THREAD

**Issue by gxcsoccer** [node-modules/cluster-client#26]
```js
 test/watcher.test.js
2017-05-03 15:37:21,506 WARN 32478 warn12345
    ✓ should work if config.watcher.type is custom (1676ms)
Error: /Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/test/fixtures/apps/watcher-custom-event-source/logs/watcher-custom-event-source/common-error.log log stream had been closed
    at FileTransport.log (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._egg-logger@1.6.0@egg-logger/lib/transports/file.js:57:19)
    at Map.log (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._egg-logger@1.6.0@egg-logger/lib/logger.js:73:19)
    at Map.log (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._egg-logger@1.6.0@egg-logger/lib/logger.js:67:22)
    at Map.Logger.(anonymous function) [as error] (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._egg-logger@1.6.0@egg-logger/lib/logger.js:141:10)
    at Object.callback (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:176:21)
    at Connection._cleanInvokes (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:121:11)
    at Connection._handleClose (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:110:10)
    at Socket.Connection._socket.on (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:30:43)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)
2017-05-03 15:37:22,527 ERROR 32478 nodejs.ClusterSocketCloseError: The socket was closed.
    at Connection._cleanInvokes (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:116:13)
    at Connection._handleClose (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:110:10)
    at Socket.Connection._socket.on (/Users/gaoxiaochen/projj/github.com/eggjs/egg-watcher/node_modules/._cluster-client@1.6.3@cluster-client/lib/connection.js:30:43)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)
name: 'ClusterSocketCloseError'
pid: 32478
hostname: gaoxiaochendeMacBook-Pro.local
```

https://travis-ci.org/eggjs/egg-watcher/jobs/228198144

**Comment by gxcsoccer** [comment]
leader 在关闭前发送了一个请求给 follower，连接关闭导致请求失败，这个时候应该判断下 leader 是否已经关闭，如果已经关闭就忽略掉。目前的是打了一个 error 日志

cc: @popomore

**Comment by popomore** [comment]
不明白在做关闭操作的时候为啥还要发一个错误请求？
