### ISSUE TITLE
 nodejs.ClusterClientConnectTimeoutError

### ISSUE THREAD

**Issue by 1166544** [node-modules/cluster-client#41]
2018-05-03 09:20:29,856 WARN 6632 nodejs.ClusterClientConnectTimeoutError: socket#127.0.0.1:50043 connect timeout(1000ms)
    at Socket.socket.setTimeout (...\node_modules\cluster-client\lib\server.js:205:19)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientConnectTimeoutError'
pid: 6632

**Comment by jamesliauw** [comment]
?

**Comment by polunzh** [comment]
Same error, hope to get a response.

**Comment by leotian** [comment]
Same error

**Comment by atian25** [comment]
这样的问题是没法解答的，要提供复现方式
